services:
  xray:
    build:
      context: ./docker/xray
    container_name: "xray"
    restart: unless-stopped
    ports:
      - "443:443"
    environment:
      - UUID=${UUID}
      - DEST=${DEST}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - SRI=${SRI}
    volumes:
      - ./docker/xray/config.json.tpl:/etc/xray/config.json.tpl
